"""This file is generated by "data/build_code.py"
It has been set to read only so that you don't edit it without using
build_code.py.
"""

from sqlalchemy import Column, Integer, String
from sqlalchemy import ForeignKey
from sqlalchemy.orm import relationship

from base_classes import Base

ATTRIBUTE_INFORMATION = [
    ("Agility", "A measure of how skilfully you can move."),
    ("Brawn", "A measure of how strong you are."),
    ("Charisma", "A measure of how well you interact with other people"),
    ("Divinity", "A measure of your connection with the spirit world."),
    ("Fortuity", "A measure of your luck."),
    ("Intellect", "A measure of your mental prowess and knowledge."),
    ("Pathfinding", "A measure of your ability to traverse the world."),
    ("Quickness", "A measure of how fast you can move."),
    ("Resilience", "A measure of how tough you are."),
    ("Survivalism", "A measure of how well you can adapt to your surroundings."),
    ("Vitality", "A measure of how healthy you are."),
    ("Willpower", "A measure of how disciplined you are.")
]

ALL_ATTRIBUTES = [attrib[0].lower() for attrib in ATTRIBUTE_INFORMATION]


class Attributes(Base):
    __tablename__ = 'attributes'
    
    id = Column(Integer, primary_key=True)

    # Relationships
    # Hero class is one to one.
    hero_id = Column(Integer, ForeignKey('hero.id', ondelete="CASCADE"))

    # Attribute class
    agility = relationship("Attribute", uselist=False, foreign_keys="[Attribute.agility_id]", cascade="all, delete-orphan")
    brawn = relationship("Attribute", uselist=False, foreign_keys="[Attribute.brawn_id]", cascade="all, delete-orphan")
    charisma = relationship("Attribute", uselist=False, foreign_keys="[Attribute.charisma_id]", cascade="all, delete-orphan")
    divinity = relationship("Attribute", uselist=False, foreign_keys="[Attribute.divinity_id]", cascade="all, delete-orphan")
    fortuity = relationship("Attribute", uselist=False, foreign_keys="[Attribute.fortuity_id]", cascade="all, delete-orphan")
    intellect = relationship("Attribute", uselist=False, foreign_keys="[Attribute.intellect_id]", cascade="all, delete-orphan")
    pathfinding = relationship("Attribute", uselist=False, foreign_keys="[Attribute.pathfinding_id]", cascade="all, delete-orphan")
    quickness = relationship("Attribute", uselist=False, foreign_keys="[Attribute.quickness_id]", cascade="all, delete-orphan")
    resilience = relationship("Attribute", uselist=False, foreign_keys="[Attribute.resilience_id]", cascade="all, delete-orphan")
    survivalism = relationship("Attribute", uselist=False, foreign_keys="[Attribute.survivalism_id]", cascade="all, delete-orphan")
    vitality = relationship("Attribute", uselist=False, foreign_keys="[Attribute.vitality_id]", cascade="all, delete-orphan")
    willpower = relationship("Attribute", uselist=False, foreign_keys="[Attribute.willpower_id]", cascade="all, delete-orphan")

    # Hero class
    # One Hero -> one Attributes object
    hero = relationship("Hero", back_populates='attributes', uselist=False)

    def __init__(self):
        self.agility = Attribute("Agility", "A measure of how skilfully you can move.")
        self.brawn = Attribute("Brawn", "A measure of how strong you are.")
        self.charisma = Attribute("Charisma", "A measure of how well you interact with other people")
        self.divinity = Attribute("Divinity", "A measure of your connection with the spirit world.")
        self.fortuity = Attribute("Fortuity", "A measure of your luck.")
        self.intellect = Attribute("Intellect", "A measure of your mental prowess and knowledge.")
        self.pathfinding = Attribute("Pathfinding", "A measure of your ability to traverse the world.")
        self.quickness = Attribute("Quickness", "A measure of how fast you can move.")
        self.resilience = Attribute("Resilience", "A measure of how tough you are.")
        self.survivalism = Attribute("Survivalism", "A measure of how well you can adapt to your surroundings.")
        self.vitality = Attribute("Vitality", "A measure of how healthy you are.")
        self.willpower = Attribute("Willpower", "A measure of how disciplined you are.")

    def items(self):
        """Returns a list of 2-tuples

        Basically a dict.items() clone that looks like ([(key, value), (key, value), ...])
        """
        return ((key, getattr(self, key)) for key in ALL_ATTRIBUTES)

    def __iter__(self):
        return (getattr(self, key) for key in ALL_ATTRIBUTES)

        
class Attribute(Base):
    """Attribute class that stores data about a hero object.
    """
    __tablename__ = "attribute"
    
    id = Column(Integer, primary_key=True)

    name = Column(String(50))
    description = Column(String(100))
    level = Column(Integer)

    # Relationships
    agility_id = Column(
        Integer, ForeignKey('attributes.id', ondelete="CASCADE"))
    brawn_id = Column(
        Integer, ForeignKey('attributes.id', ondelete="CASCADE"))
    charisma_id = Column(
        Integer, ForeignKey('attributes.id', ondelete="CASCADE"))
    divinity_id = Column(
        Integer, ForeignKey('attributes.id', ondelete="CASCADE"))
    fortuity_id = Column(
        Integer, ForeignKey('attributes.id', ondelete="CASCADE"))
    intellect_id = Column(
        Integer, ForeignKey('attributes.id', ondelete="CASCADE"))
    pathfinding_id = Column(
        Integer, ForeignKey('attributes.id', ondelete="CASCADE"))
    quickness_id = Column(
        Integer, ForeignKey('attributes.id', ondelete="CASCADE"))
    resilience_id = Column(
        Integer, ForeignKey('attributes.id', ondelete="CASCADE"))
    survivalism_id = Column(
        Integer, ForeignKey('attributes.id', ondelete="CASCADE"))
    vitality_id = Column(
        Integer, ForeignKey('attributes.id', ondelete="CASCADE"))
    willpower_id = Column(
        Integer, ForeignKey('attributes.id', ondelete="CASCADE"))
    
    def __init__(self, name, description):
        """Build the initial Attribute object.
        
        Set all values to 1.
        """
        
        self.name = name
        self.description = description
        self.level = 1
