USE `test`;

DROP TABLE IF EXISTS `quest_path_to_quest_association`;
DROP TABLE IF EXISTS `quest`;
DROP TABLE IF EXISTS `quest_path`;
DROP TABLE IF EXISTS `condition_to_trigger`;
DROP TABLE IF EXISTS `condition`;
DROP TABLE IF EXISTS `handler`;
DROP TABLE IF EXISTS `trigger_to_hero`;
DROP TABLE IF EXISTS `trigger`;
DROP table IF EXISTS `achievement`;
DROP table IF EXISTS `achievements`;
DROP TABLE IF EXISTS `journal`;
DROP TABLE IF EXISTS `proficiency`;
DROP TABLE IF EXISTS `ability`;
DROP TABLE IF EXISTS `attribute`;
DROP TABLE IF EXISTS `item`;
DROP TABLE IF EXISTS `inventory`;
DROP TABLE IF EXISTS `specialization`;
DROP TABLE IF EXISTS `hero`;
