"""
This file is generated by 'build_code.py'.
It has been set to read only so that you don't edit it without using
'build_code.py'. Thought that may change in the future.
"""


class Pig:
    def __init__(self):
        pass

    def bite(self):
        print("The Beast does {}!".format('bite'))

    def snarl(self):
        print("The Beast does {}!".format('snarl'))

    def kill(self):
        print("The Beast does {}!".format('kill'))



class Dog:
    def __init__(self):
        pass

    def bite(self):
        print("The Beast does {}!".format('bite'))

    def snarl(self):
        print("The Beast does {}!".format('snarl'))

    def kill(self):
        print("The Beast does {}!".format('kill'))



class Biltong:
    def __init__(self):
        pass

    def bite(self):
        print("The Beast does {}!".format('bite'))

    def snarl(self):
        print("The Beast does {}!".format('snarl'))

    def kill(self):
        print("The Beast does {}!".format('kill'))



